[package]
name = "pheasant_core"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dev"
path = "src/main.rs"

[dependencies]
crossbeam-channel = "0.5.15"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tobytes = "0.1.0"
tokio = { version = "1.46.1", features = ["full"] }
